src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email."
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", unique=true, nullable=true)
     */
    private $apiToken;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 3,
     *      max = 15,
     *      minMessage = "Your last name must be at least {{ limit }} characters long",
     *      maxMessage = "Your last name cannot be longer than {{ limit }} characters"
     * )
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 3,
     *      max = 15,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters"
     * )
     */
    private $first_name;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThan(17)
     */
    private $age;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getTokenApi(): ?string
    {
        return $this->apiToken;
    }

    public function setTokenApi($apiToken): self
    {
        $this->apiToken = $apiToken;
        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }
}

src/Form/UserType.php
<?php
    namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class UserType extends AbstractType {
    public function buildForm( FormBuilderInterface $builder, array $options) {
        $builder
        ->add('first_name', TextType::class, [
            'attr' => [
                'placeholder' => 'Your First name'
            ]
        ])
        ->add('last_name', TextType::class, [
            'attr' => [
                'placeholder' => 'Your Last name'
            ]
        ])
        ->add('email', EmailType::class, [
            'attr' => [
                'placeholder' => 'exemple@exemple.com'
            ]
        ])
        ->add('password', PasswordType::class, [
            'attr' => [
                'placeholder' => 'Your password'
            ]
        ])
        ->add('age', NumberType::class, [
            'attr' => [
                'placeholder' => 'Your age exp: 18'
            ]
        ])
        ->add('submit', SubmitType::class, [
            'attr' => [
                'class' => 'fluid'
            ]
        ])
        ->getForm();
    }
}


?>

templates/user/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}
    Edit Account
{% endblock %}

{% block body %}
<center><h1>Edit Your Account</h1></center>
    <div class="act-form-container">
        {{form(form)}}
    </div>

{% endblock %}

templates/user/home.html.twig
{% extends "base.html.twig" %}
{% block title %}
    Profile
{% endblock %}



{% block body %}

    {% for msg in app.flashes('notice') %}
<div class="ui success message">
        <div class="header">
            Action succeeded
        </div>
        <p>
        {{msg}}
        </p>
    </div>
{% endfor %}

    {% if app.user.roles.0 == 'ROLE_ADMIN' %}
        <center><h1>Hello Admin " {{app.user.firstName ~ ' ' ~ app.user.lastName}} "</h1></center>
        <br>
    {% else %}
        <center><h1>Hello Mr(s) {{app.user.firstName ~ ' ' ~ app.user.lastName}} this is your account data</h1></center>
        <br>
    {% endif %}


    <div class="ui two column grid">
    <div class="column">
        <div class="user-details-container">
            <div class="ui two column grid">
                <div class="column">
                    User ID:
                </div>
                <div class="column">
                    {{app.user.id}}
                </div>
            </div>
            <div class="ui two column grid">
                <div class="column">
                    User First Name:
                </div>
                <div class="column">
                    {{app.user.firstName}}
                </div>
            </div>
            <div class="ui two column grid">
                <div class="column">
                    User Last Name:
                </div>
                <div class="column">
                    {{app.user.lastName}}
                </div>
            </div>
            <div class="ui two column grid">
                <div class="column">
                    User Age:
                </div>
                <div class="column">
                    {{app.user.age}}
                </div>
            </div>
            <div class="ui two column grid">
                <div class="column">
                    User Email:
                </div>
                <div class="column">
                    {{app.user.email}}
                </div>
            </div>
        </div>
    </div>
    <div class="column"></div>
</div>

  <br>
&nbsp;&nbsp;
<a class="return-link" href="{{path('users_list')}}">
    View Users list
    &nbsp;
    <i class="external icon"></i>
</a>
&nbsp;&nbsp;
<a class="return-link" href="{{path('user_edit')}}">
    Edit Account
    &nbsp;
    <i class="edit icon"></i>
</a>
{% endblock %}

templates/user/sessions_date.html.twig
{% extends "base.html.twig" %}

{% block title %}
Sessions Schedule
{% endblock %}

{% block stylesheets %}
<style>
    html {
        background-color: #fefefe;
        box-sizing: border-box;
        font-family: 'Roboto', sans-serif;
        font-size: 14px;
        font-weight: 500;
    }

    *,
    *:before,
    *:after {
        box-sizing: inherit;
    }

    .cards-container {
        margin: 50px auto 0;
        width: 700px;
    }

    .u-float-right {
        float: right;
    }

    .u-flex-center {
        display: -webkit-flex;
        display: flex;
        -webkit-justify-content: center;
        justify-content: center;
        -webkit-align-items: center;
        align-items: center;
    }

    .subtle {
        color: #888;
        font-size: 12px;
    }

    .card-media {
        border-radius: 2px;
        box-shadow: 0 2px 8px rgba(0, 0, 0, .12);
        height: 125px;
        margin-bottom: 25px;
        transition: all 300ms ease-out;
        width: 100%;
    }

    .card-media:hover {
        box-shadow: 0 5px 14px rgba(0, 0, 0, .2);
    }

    .card-media-object-container {
        background: none;
        float: left;
        height: 100%;
        width: 35%;
        position: relative;
    }

    .card-media-object {
        background-position: center center;
        background-size: cover;
        height: 100%;
    }

    .card-media-object:after {
        content: " ";
        display: block;
        height: 100%;
        left: 0;
        opacity: 0;
        position: absolute;
        right: 0;
        top: 0;
        transition: all 300ms ease-out;
        z-index: 10;
    }

    .card-media:hover .card-media-object:after {
        background: -moz-linear-gradient(top, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0) 52%, rgba(0, 0, 0, 0.4) 100%);
        background: -webkit-linear-gradient(top, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0) 52%, rgba(0, 0, 0, 0.4) 100%);
        background: linear-gradient(to bottom, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0) 52%, rgba(0, 0, 0, 0.4) 100%);
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#00000000', endColorstr='#a6000000', GradientType=0);
        opacity: 1;
    }

    .card-media-object-tag {
        background-color: #fff;
        border-radius: 2px;
        padding: 2px 7px;
        position: absolute;
        right: 10px;
        top: 10px;
    }

    .card-media-object-social-list {
        bottom: 4px;
        left: 10px;
        list-style-type: none;
        margin: 0;
        padding: 0;
        position: absolute;
        z-index: 20;
    }

    .card-media-object-social-list li {
        border-radius: 50%;
        display: inline-block;
        height: 30px;
        margin-right: 6px;
        opacity: 0;
        overflow: hidden;
        transform: translateY(5px);
        transition: all 300ms ease-out;
        width: 30px;
    }

    .card-media:hover .card-media-object-social-list li {
        opacity: 1;
        transform: translateY(0);
    }

    .card-media-object-social-list li:nth-child(1) {
        transition-delay: 0;
    }

    .card-media-object-social-list li:nth-child(2) {
        transition-delay: 75ms;
    }

    .card-media-object-social-list li:nth-child(3) {
        transition-delay: 150ms;
    }

    .card-media-object-social-list-item-additional {
        border: 1px solid #fff;
        color: #fff;
        font-size: 12px;
        padding-top: 7px;
        text-align: center;
    }

    .card-media-body {
        background-color: #fff;
        float: left;
        height: 100%;
        padding: 12px 15px;
        position: relative;
        width: 65%;
    }

    .card-media-body-top {
        display: block;
    }

    .card-media-body-top-icons {
        margin-top: -2px;
        opacity: 0;
        transition: all 300ms ease-out;
        transform: translateY(-5px);
    }

    .card-media:hover .card-media-body-top-icons {
        opacity: 1;
        transform: translateY(0);
    }

    .card-media-body-top-icons>svg {
        cursor: pointer;
        margin-left: 10px;
        transition: all 300ms ease-out;
    }

    .card-media-body-top-icons>svg:hover {
        fill: #444;
    }

    .card-media-body-heading {
        display: block;
        margin-top: 10px;
    }

    .card-media-body-supporting-bottom {
        position: absolute;
        bottom: 10px;
        left: 0;
        opacity: 1;
        padding: 0 15px;
        transition: all 300ms ease-out;
        width: 100%;
    }

    .card-media:hover .card-media-body-supporting-bottom {
        opacity: 0;
        transform: translateY(-8px);
    }

    .card-media-body-supporting-bottom-text {
        display: inline-block;
    }

    .card-media-body-supporting-bottom-reveal {
        opacity: 0;
        transform: translateY(8px);
        transition: all 300ms ease-out;
    }

    .card-media:hover .card-media-body-supporting-bottom-reveal {
        opacity: 1;
        transform: translateY(0);
    }

    .card-media-link {
        color: #41C1F2;
        text-decoration: none;
    }
</style>
{% endblock %}

{% block body %}


{% for session in sessions %}

<div class="cards-container">

    <div class="card-media">
        <!-- media container -->
        <div class="card-media-object-container">
            <div class="card-media-object" style="background-image: url(https://s9.postimg.cc/y0sfm95gv/prince_f.jpg);">
            </div>
            <span class="card-media-object-tag subtle"> {{session.CodeCo}} </span>
            <ul class="card-media-object-social-list">
                <li>
                    <img src="https://s10.postimg.cc/3rjjbzcvd/profile_f.jpg" class="">
                </li>
                <li>
                    <img src="https://s16.postimg.cc/b0j0djh79/profile_0_f.jpg" class="">
                </li>
                <li class="card-media-object-social-list-item-additional">
                    <span>+2</span>
                </li>
            </ul>
        </div>
        <!-- body container -->
        <div class="card-media-body">
            <div class="card-media-body-top">
                <span class="subtle">{{session.DateSe|date}}</span>
                <div class="card-media-body-top-icons u-float-right">
                    <svg fill="#888888" height="16" viewBox="0 0 24 24" width="16" xmlns="http://www.w3.org/2000/svg">
                        <path d="M0 0h24v24H0z" fill="none" />
                        <path
                            d="M18 16.08c-.76 0-1.44.3-1.96.77L8.91 12.7c.05-.23.09-.46.09-.7s-.04-.47-.09-.7l7.05-4.11c.54.5 1.25.81 2.04.81 1.66 0 3-1.34 3-3s-1.34-3-3-3-3 1.34-3 3c0 .24.04.47.09.7L8.04 9.81C7.5 9.31 6.79 9 6 9c-1.66 0-3 1.34-3 3s1.34 3 3 3c.79 0 1.5-.31 2.04-.81l7.12 4.16c-.05.21-.08.43-.08.65 0 1.61 1.31 2.92 2.92 2.92 1.61 0 2.92-1.31 2.92-2.92s-1.31-2.92-2.92-2.92z" />
                    </svg>
                    <svg fill="#888888" height="16" viewBox="0 0 24 24" width="16" xmlns="http://www.w3.org/2000/svg">
                        <path d="M17 3H7c-1.1 0-1.99.9-1.99 2L5 21l7-3 7 3V5c0-1.1-.9-2-2-2z" />
                        <path d="M0 0h24v24H0z" fill="none" />
                    </svg>
                </div>
            </div>
            <span class="card-media-body-heading">{{session.CodaAct}}</span>
            <div class="card-media-body-supporting-bottom">
                <span class="card-media-body-supporting-bottom-text subtle">Mezzanine, San Francisco, CA</span>
                <span class="card-media-body-supporting-bottom-text subtle u-float-right">Free &ndash; $30</span>
            </div>
            <div class="card-media-body-supporting-bottom card-media-body-supporting-bottom-reveal">
                <span class="card-media-body-supporting-bottom-text subtle">#Music #Party</span>
                <a href="#/" class="card-media-body-supporting-bottom-text card-media-link u-float-right more-details"
                    id="{{session.id}}" onclick="openModal(id)">
                    More Details
                </a>
            </div>
        </div>
    </div>

</div>

<!-- Details modal -->

<div class="ui modal modal-{{session.id}}">
    <i class="close icon"></i>
    <div class="header">
        Session Details
    </div>
    <div class="content">
        <div class="ui two column grid">
            <div class="column">
                Start At :
            </div>
            <div class="column">
                {{session.heureDebut|date}}
            </div>
        </div>

        <div class="ui two column grid">
            <div class="column">
                End At :
            </div>
            <div class="column">
                {{session.heureFin|date}}
            </div>
        </div>
    </div>
    <div class="actions">
        <div class="ui approve button">Ok</div>
        <div class="ui cancel button">Cancel</div>
    </div>
</div>

{% endfor %}

{% endblock %}

{% block javascripts %}
<script>
    function openModal(id) {
       
        $('.ui.modal.modal-'+id)
            .modal('show')
            ;
    }


</script>
{% endblock %}

templates/user/users_list.html.twig
{% extends "base.html.twig" %}

{% block title %}
Users
{% endblock %}

{% block body %}
<center>
    <h1>Cluby Users</h1>
</center>
<br><br><br>
<div class="user-container">
    <div class="ui one column grid">
        <div class="column">
            <div class="ui cards">
                {% for user in users %}
                <div class="card stackable {% if user.roles.0 == 'ROLE_ADMIN' %} orange {% else %} blue {% endif %}">
                    <div class="image">
                        <img src="{{ random([asset('images/user/user-female-2.png'), asset('images/user/user-female-icon.png'), asset('images/user/user-male-icon.png')]) }}"
                            alt="User image">
                    </div>
                    <div class="content">
                        <a class="header">
                            
                                {{user.firstName ~ ' ' ~ user.lastName}}
                                {% if user.roles.0 == 'ROLE_ADMIN' %}
                                <span data-tooltip="Admin" data-inverted="">
                                    <i class="star icon"></i>
                                </span>
                                    
                                {% endif %}
                            </a>
                        <div class="meta">
                            <span class="date">Joined in 2020</span>
                        </div>
                        <div class="description">
                            {{user.firstName ~ ' ' ~ user.lastName}} is an art director living in New York.
                        </div>
                    </div>
                    <div class="extra content">
                        <a>
                            <i class="mail icon"></i>
                            {% if user.roles.0 == 'ROLE_ADMIN' %}
                                Contact@cluby_admin.com
                            {% else %}
                                {{user.email}}
                            {% endif %}
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}